apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-example
  labels:
    app: java-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-example
  template:
    metadata:
      labels:
        app: java-example
    spec:
      containers:
      - name: java-example
        image: registry.accordions.co.kr/exa:test
        imagePullPolicy: Always
        securityContext:
          runAsUser: 0
          allowPrivilegeEscalation: true
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        envFrom:
        - configMapRef:
            name: java-example-config
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30 