apiVersion: v1
kind: Service
metadata:
  name: java-example
  labels:
    app: java-example
spec:
  selector:
    app: java-example
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32223
  type: NodePort